require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

RSpec/SpecFilePathFormat:
  CustomTransform:
    MuPDF: mupdf

Naming/MethodParameterName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
